### ISSUE TITLE
SDAnimatedImage assumed to be @MainActor isolated by Swift, needs NS_SWIFT_NONISOLATED macro and possibly NS_SWIFT_SENDABLE if applicable

### ISSUE THREAD

**Issue by LeoTheCatMeow** [SDWebImage/SDWebImage#3729] opened 2024-07-21 22:06 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 15.0+
 SDWebImage Version      | any latest
 Integration Method      | SPM
 Xcode Version           | Xcode 15.4
 Repro rate              | 100%
<img width="1213" alt="Screenshot 2024-07-21 at 5 54 38 PM" src="https://github.com/user-attachments/assets/555f7f5f-041f-4cb6-a350-321e3785b5f1">
<img width="1354" alt="Screenshot 2024-07-21 at 5 54 53 PM" src="https://github.com/user-attachments/assets/e792ff26-c02d-4517-9dad-746eecdc0e89">
<img width="1335" alt="Screenshot 2024-07-21 at 5 55 37 PM" src="https://github.com/user-attachments/assets/d59e1720-f142-445c-8852-68849abc2889">
<img width="1320" alt="Screenshot 2024-07-21 at 5 55 21 PM" src="https://github.com/user-attachments/assets/4e2bc1b4-a4fb-436f-b64c-6fd4ac594a78">

### Issue Description and Steps

With the addition of Swift concurrency, a simple subclass of UIImage written in Objc is assumed by Swift compiler as `@MainActor` isolated, which throws all sorts of warnings with concurrency checking enabled when you create `SDAnimatedImage` in some `@Sendable` closure such as `DispatchQueue.global().async`. Obviously, it is safe to create SDAnimatedImage on a non-main thread, but Swift compiler is complaining about this. On the Objc side, could we add NS_SWIFT_NONISOLATED macro to disable the compiler complaint, and possibly NS_SWIFT_SENDABLE if `SDAnimatedImage` could be considered Sendable? Thanks. 

Other public classes of SDWebImage probably could use the same macros as well, depending on the use case.

**Comment by dreampiggy** [comment] 2024-07-22 03:46
> Obviously, it is safe to create SDAnimatedImage on a non-main thread, but Swift compiler is complaining about this.

By design. This object and `UIImage` is not MainActor. It can be created on any Thread.

**Comment by dreampiggy** [comment] 2024-07-22 03:47
I think the bug is that UIKit team annoate the wrong `@MainActor` on `UIImage`, it's wrong.

**Comment by LeoTheCatMeow** [comment] 2024-07-22 03:52
@dreampiggy UIImage is actually not annotated with `@MainActor` and is safe to use in non-isolated context, it is also marked as Sendable. But any subclass of it automatically becomes bound to `@MainActor`, I think this could be more of a bug with Swift compiler itself or something. It might be possible to work around this by doing some kind of `@preconcurrency import` of SDWebImage, but that would be needed everywhere, having the fix on the actual class itself would be easier

**Comment by LeoTheCatMeow** [comment] 2024-07-22 03:53
<img width="1335" alt="image" src="https://github.com/user-attachments/assets/7a0c4532-a080-48f5-aafd-013d4cf4ccde">
Doing stuff like this does not raise any warning at all

**Comment by dreampiggy** [comment] 2024-07-22 04:07
So just mark it as `NS_SWIFT_SENDABLE` ?

I think this is hack from Swift's Compiler, I've already see some codes which check for `UIKit/SwiftUI` module

**Comment by LeoTheCatMeow** [comment] 2024-07-22 12:11
> So just mark it as `NS_SWIFT_SENDABLE` ?
> 
> I think this is hack from Swift's Compiler, I've already see some codes which check for `UIKit/SwiftUI` module

You can see the original issue description, this macro `NS_SWIFT_NONISOLATED` will suppress the warning, while `NS_SWIFT_SENDABLE ` adds a `@unchecked Sendable` to the Swift interface, but does not actually suppress the warning. So basically, the macro is needed is `NS_SWIFT_NONISOLATED`, `NS_SWIFT_SENDABLE` only tells Swift that this  class is safe to cross from one thread to another.

I encounter this issue on Xcode 15.4, I haven't checked Xcode 16 yet, I wonder if anyone else encounters this issue? Is this a Swift Compiler bug, is there some compiler flag that can be used to avoid this? I wonder..

**Comment by dreampiggy** [comment] 2024-07-22 12:16
> which throws all sorts of warnings with concurrency checking enabled when you create SDAnimatedImage in some @Sendable closure such as DispatchQueue.global().async

Any Swift Demo ? I can use a simple demo to reproduce on Xcode 16-Beta3

Anyway, the simple marker seems fix the issue.
Our SD whole codebase has many `UIImage` subclass except this `SDAnimatedImage`

and also, some legacy repo like `LottieImage` in  https://github.com/SDWebImage/SDWebImageLottieCoder, `SDYYImage` in https://github.com/SDWebImage/SDWebImageYYPlugin)

**Comment by LeoTheCatMeow** [comment] 2024-07-22 12:21
@dreampiggy 
<img width="1347" alt="image" src="https://github.com/user-attachments/assets/01cf5f3f-9935-4cf1-a3a9-ac3dcfcd2607">
You can see rough example like this one

**Comment by dreampiggy** [comment] 2024-07-22 12:30
Seems SPM can not use this xcconfig ? I have to modify some trick about project configuration

This becomes error only if you upgrade the `SWIFT_VERSION` to 6, like:

<img width="1488" alt="截屏2024-07-22 20 30 00" src="https://github.com/user-attachments/assets/58185783-7f7c-4970-94c6-7762db992a4c">


We somehow added the hardcode in Podspec and Package.swift to limit this.

**Comment by dreampiggy** [comment] 2024-07-22 12:32
How to `Disable` the `@MainActor`, actually I want to know ?

For subclassing

**Comment by LeoTheCatMeow** [comment] 2024-07-22 12:32
Yes this is only a hard error on Swift6, Swift5 only treats it as soft waring. The root of the issue is of course... the stupid compiler treating SDAnimatedImage as being marked as `@MainActor`

**Comment by LeoTheCatMeow** [comment] 2024-07-22 12:33
> How to `Disable` the `@MainActor`, actually I want to know ?
> 
> For subclassing
<img width="1335" alt="Screenshot 2024-07-21 at 5 55 37 PM" src="https://github.com/user-attachments/assets/9124e4e9-f531-4694-81e7-8c0f6618546e">

Here's the simple example I provided with Objc code. This is what I found so far, it is an annotation placed on a class

**Comment by dreampiggy** [comment] 2024-07-22 12:42
The `NS_SWIFT_NONISOLATED` seems fix some issues, but still not work on my Xcode 16 Beta 3 environment.
<img width="1347" alt="350962045-01cf5f3f-9935-4cf1-a3a9-ac3dcfcd2607" src="https://github.com/user-attachments/assets/ed8e2a9c-2b38-4971-8d43-49a53b58cbd7">





I think there are some compiler magic in the implementation, maybe hint like`__SWIFT_ATTR_SUPPORTS_SENDABLE_DECLS`

```
#if __SWIFT_ATTR_SUPPORTS_SENDABLE_DECLS
   // Indicates that the thing it is applied to should be imported as 'Sendable' in Swift:
   // * Type declarations are imported into Swift with a 'Sendable' conformance.
   // * Block parameters are imported into Swift with an '@Sendable' function type. (Write it in the same place you would put 'NS_NOESCAPE'.)
   // * 'id' parameters are imported into Swift as 'Sendable', not 'Any'.
   // * Other object-type parameters are imported into Swift with an '& Sendable' requirement.
#  define NS_SWIFT_SENDABLE __attribute__((swift_attr("@Sendable")))

   // Indicates that the thing it is applied to should *not* be imported as 'Sendable' in Swift even if it normally would be.
#  define NS_SWIFT_NONSENDABLE __attribute__((swift_attr("@_nonSendable")))

   // Indicates that a specific member of an 'NS_SWIFT_UI_ACTOR'-isolated type is "threadsafe" and should be callable from outside the main actor.
#  define NS_SWIFT_NONISOLATED __attribute__((swift_attr("nonisolated")))

#  define __NS_HEADER_AUDIT_BEGIN_sendability \
    _Pragma("clang diagnostic push") \
    _Pragma("clang diagnostic ignored \"-Wpragma-clang-attribute\"") \
    _Pragma("clang attribute NS_HEADER_AUDIT_sendability.push (__attribute__((swift_attr(\"@_nonSendable(_assumed)\"))), apply_to = any(objc_interface, record, enum))") \
    _Pragma("clang diagnostic pop")

#  define __NS_HEADER_AUDIT_END_sendability   _Pragma("clang attribute NS_HEADER_AUDIT_sendability.pop")
#else
#  define NS_SWIFT_SENDABLE
#  define NS_SWIFT_NONSENDABLE
#  define NS_SWIFT_NONISOLATED

#  define __NS_HEADER_AUDIT_BEGIN_sendability
#  define __NS_HEADER_AUDIT_END_sendability
#endif
```

**Comment by LeoTheCatMeow** [comment] 2024-07-22 12:46
> The `NS_SWIFT_NONISOLATED` seems fix some issues, but still not work on my Xcode 16 Beta 3 environment.

Oh please ignore the other error. The error you have left now is saying that the onLoaded function should be marked as `@Sendable`, because it got dispatched to a global queue. This is not a bug with SDAnimatedImage, this is just a small code error. It should be fixed on the user's side.

**Comment by dreampiggy** [comment] 2024-07-22 12:49
OK.

But another issue. Seems this `NS_SWIFT_NONISOLATED` is only available from Xcode 15 SDK

For old version, maybe I still need to polify to expand this to `none`. Like Xcode 14 (Do we need ?)

**Comment by LeoTheCatMeow** [comment] 2024-07-22 12:51
Thanks a lot! I tried to look up this issue and cannot find any results online yet. This is definitely a bug caused by Apple, and our current solution is only a workaround. I'll research more and see if there's any discussion about this. Possibly a bug reported should be filed to the Swift team...

**Comment by dreampiggy** [comment] 2024-07-22 12:51
This `SDGraphicsImageRenderer`, is actually wrapper for `UIGraphicsImageRendererFormat`

Should marked as `NS_SWIFT_SENDABLE` as well ?
<img width="858" alt="截屏2024-07-22 20 51 19" src="https://github.com/user-attachments/assets/22d20c15-e673-41d5-92e9-665aa3c93897">

**Comment by dreampiggy** [comment] 2024-07-22 12:53
A question:

If I don't annoate anything, and just subclass from `NSObject`

How do Swift compiler knows whether it's sendable or not ? What's the imported type in Swift shows ?

**Comment by LeoTheCatMeow** [comment] 2024-07-22 12:54
> A question:
> 
> If I don't annoate anything, and just subclass from `NSObject`
> 
> How do Swift compiler knows whether it's sendable or not ? What's the imported type in Swift shows ?

It does not know, I think. This is my Apple's has been annotating their code. Adding the macro just applies a `@unchecked Sendable` to the class interface in Swift

**Comment by dreampiggy** [comment] 2024-07-22 12:57
> > A question:
> > If I don't annoate anything, and just subclass from `NSObject`
> > How do Swift compiler knows whether it's sendable or not ? What's the imported type in Swift shows ?
> 
> It does not know, I think. This is why Apple's has been annotating their code. Adding the macro just applies a `@unchecked Sendable` to the class interface in Swift

Seems, the compiler import that `A type which only inherited from NSObject`, without any Sendable attribute

<img width="736" alt="截屏2024-07-22 20 56 48" src="https://github.com/user-attachments/assets/6b2ea60d-417d-4cd4-99fa-07b793119b51">

**Comment by dreampiggy** [comment] 2024-07-22 12:58
Seems a huge work to do if `Any NSObject subclass` need to mark sendable or not.

Currently just quick fix the `SDAnimatedImage` in the next patch version.

See: PR

**Comment by LeoTheCatMeow** [comment] 2024-07-22 12:59
> Seems a huge work to do if `Any NSObject subclass` need to mark sendable or not.
> 
> Currently just quick fix the `SDAnimatedImage` in the next patch version.
> 
> See: PR

Yeah I think there is no need to go through the trouble of handling all the Sendable or not question. Sendable is only a marker protocol, basically users of the library can mark it if they really want to.

**Closed** 2024-07-23 06:31 UTC
Labels: swift, concurrency
