### ISSUE TITLE
[Decompressor] Error -17102 decompressing image -- possibly corrupt after updating to v5.13 for PNG image

### ISSUE THREAD

**Issue by randarnold** [SDWebImage/SDWebImage#3365] opened 2022-06-29 20:53 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name         |  iOS
 Platform Version        | 16.0 (simulator)
 SDWebImage Version    |  5.13
 Integration Method   |   spm
 Xcode Version          | 14.0 beta 2 (14A5229c)
 Repro rate            | 100%
 Repro with our demo prj | n/a
 Demo project link      

### Issue Description and Steps

After updating SDWebImage to v 5.13 my images repeatedly flash and
[Decompressor] Error -17102 decompressing image -- possibly corrupt
shows up in the log.

Reverting to v5.12.6 solves the problem.

Not sure if I'm missing a new configuration setting related to the new decompression changes? https://github.com/SDWebImage/SDWebImage/pull/3355

Anybody else seeing this?

**Comment by danielmillipede** [comment] 2022-07-08 04:32
Yes, I am seeing this too in the SPM installation v5.13

**Comment by dreampiggy** [comment] 2022-07-08 06:55
From the log, YES it's outputed from Apple's ImageIO.

Can you provide such case of sample Image URL ? @danielmillipede @randarnold

**Comment by dreampiggy** [comment] 2022-07-08 07:21
Hi. For simple fix, we need sample to filter those **broken image**. Please submit the url or attachment here for me to invesigate.

For another fix, we can introduce something like:

```swift
enum SDImageCoderHelper.defaultForceDecodeSolution {
    case automatic
    case coreGraphics // always use the CoreGraphics to redraw on bitmap context
    case uikit // available on iOS/tvOS 15+, use UIKit's new CGImageDecompressor
}
```

**Comment by dreampiggy** [comment] 2022-07-08 07:27
The iOS 15+ CGImageDecompressor based on the `/System/Library/PrivateFrameworks/CMPhoto.framework/CMPhoto` private framework. Which is not CoreGraphics based.

**Comment by randarnold** [comment] 2022-07-08 14:27
@dreampiggy I'm away for a few days, I will work on this when I return. Thank you for taking a look.

> From the log, YES it's outputed from Apple's ImageIO.
> 
> Can you provide such case of sample Image URL ? @danielmillipede @randarnold

**Comment by jiasongs** [comment] 2022-07-11 01:02
same issue

**Comment by dreampiggy** [comment] 2022-07-11 06:31
The memory you use is `In App Memory`, not the `Total Memory OS && App use`

When using the old `CGBitmapContext` draw decode, Core Graphics will use the **CARenderServer** (which is an OS provided daemon process), so it does not count into the RAM your App use.

But actually, it occupy the same RAM because it just transfer the footprint between 2 different processes, the totaly RAM used is the same.

**Comment by dreampiggy** [comment] 2022-07-11 08:20
Found some interesting behavior, on Simulator currently


1. `Error -17102 decompressing image -- possibly corrupt`
I can not reproduce this on the M1 arm64 simulator for that [imgae.links.txt](https://github.com/SDWebImage/SDWebImage/files/9080252/imgae.links.txt). Does this happends on some specify firmware version

2. After profile, I found that UIKit solution seems occupy more RAM than my thinking

See ths Allocation Instrument profile:
![screenshot-20220711-161542](https://user-images.githubusercontent.com/6919743/178220083-1de98b56-4ad9-4577-8a05-0c9a54a837fb.png)
![screenshot-20220711-161656](https://user-images.githubusercontent.com/6919743/178220095-b9d75f8f-d75f-4b65-bb15-937966546d65.png)

I doubt this is a Bug ? Why CoreAnimation render still create a new image, although it's produced by `UIImage.imageByPreparingForDisplay` ?

**Comment by dreampiggy** [comment] 2022-07-11 09:51
Update:

When running on iPad iOS 15.0 arm64e, the bahvior is different. It does not double the RAM usage, instead, only `1/3` RAM usage is occupied, comapred to CoreGraphics solution.

![screenshot-20220711-173950](https://user-images.githubusercontent.com/6919743/178236091-1262beb1-cd98-4750-aae7-faf4fc6ebd57.png)

### Test cases

All profiles:

1. UIKit Solution x Simulator: `2x`
2. CoreGraphics Solution x Simulator: `1x`
3. UIKit Solution x arm64 iPad `1/3x` 
4. CoreGraphics Solution x arm64 iPad `1x`

[SDWebImage-Force-Decode-Profile.zip](https://github.com/SDWebImage/SDWebImage/files/9082783/SDWebImage-Force-Decode-Profile.zip)


It turn out that using UIKit solution on device iPad, can reduce from `1x` -> `1/3x`, **-67%** RAM usage.
It turn out that using UIKit solution on simulator (bug?), can increase from `1x` -> `2x`, **+100%** RAM usage.

**Comment by randarnold** [comment] 2022-07-11 17:16
While this happens with many images, I've identified one https://d16aq3r0gw0t0n.cloudfront.net/uploads/channels/publisher/brand_logo/362/Independent_NavBar_Solid_3x.png

I can identified more if needed.

> @dreampiggy I'm away for a few days, I will work on this when I return. Thank you for taking a look.
> 
> > From the log, YES it's outputed from Apple's ImageIO.
> > Can you provide such case of sample Image URL ? @danielmillipede @randarnold

**Comment by dreampiggy** [comment] 2022-07-12 03:56
> While this happens with many images, I've identified one https://d16aq3r0gw0t0n.cloudfront.net/uploads/channels/publisher/brand_logo/362/Independent_NavBar_Solid_3x.png
> 
> I can identified more if needed.
> 
> > @dreampiggy I'm away for a few days, I will work on this when I return. Thank you for taking a look.
> > > From the log, YES it's outputed from Apple's ImageIO.
> > > Can you provide such case of sample Image URL ? @danielmillipede @randarnold

@randarnold Is this 100% reproducable ? I can not see the log when testing on iOS 16 simulator.

![image](https://user-images.githubusercontent.com/6919743/178405432-af652836-74b4-4bfb-ac84-58c178c587c6.png)

**Comment by randarnold** [comment] 2022-07-12 22:59
> @randarnold Is this 100% reproducable ? I can not see the log when testing on iOS 16 simulator.

As far as I can tell yes. Just verified with another similar image and I also get the error. I suspect this happens with all images, but I've not been able to prove that (at least yet).

I do have CGBITMAP_CONTEXT_LOG_ERRORS set to true.

**Comment by aheze** [comment] 2022-07-12 23:39
Dropping in here to say I ran into the same issue 😄

**Comment by randarnold** [comment] 2022-07-13 00:42
As far as I can tell this only happens (in my app) with png files, not jpegs.

**Comment by dreampiggy** [comment] 2022-07-14 08:40
Any new demo which can reproduce this log ?

Or, can you test your App by modifying SDWebImage's source code, that `SDImageCoder.m` to add some logs about the input `CGImage` description ?

```objective-c
CFShow(cgimage)
```

**Comment by randarnold** [comment] 2022-07-14 17:46
@dreampiggy I was finally able to reproduce with the demo app, by switching the SDWebImageView in the table view cells to a plain UIImageView. Does the decompressor rely on state that is only setup in SDWebImageView?

**Comment by dreampiggy** [comment] 2022-07-15 03:29
>  I was finally able to reproduce with the demo app, by switching the SDAnimatedImageView in the table view cells to a plain UIImageView.

I'm actually doing the same thing, UIImageView is needed because SDAnimatedImage does not use that force decoding path.

But still not reproducable.

**Comment by dreampiggy** [comment] 2022-07-15 03:52
WTF...CGImage now keep the original data buffer (PNG/JPEG data) in memory (or mmap)...

![image](https://user-images.githubusercontent.com/6919743/179146826-531472ba-e947-4204-b7c3-548ab042b920.png)

**Comment by dreampiggy** [comment] 2022-07-15 04:23
Disassembling..

1. CMPhotoDecompressionSessionCreateContainer return `0xffffbd32`
2. Because `0xffffbd32 < 0xffffbd9e`, jump to check again
3. Because `0xffffbd32 != 0xffffbd31` && `0xffffbd32 != 0xffffbd33`, call `_UIDecompressorLog` with  "Error %{0x8020100}ld decompressing image -- possibly corrupt"

**Comment by dreampiggy** [comment] 2022-07-15 05:36
I think CMPhoto is read PNG data bytes, but they found `it's not a valid PNG`

I'll check PNG standard to check whether your PNG data is valid, or can we have some check as well as them, to just filter this.

**Comment by dreampiggy** [comment] 2022-07-16 07:08
No, always failed.

There are already fallback solution to use CoreGraphics to force decode and produce the image, so from user side, there are no visible failure.

**Comment by dreampiggy** [comment] 2022-07-16 08:41
#3368 will be merged.

Which now change to decode JPEG/HEIF for `imageByPreparingForDisplay` by default

And we have new `forceDecode` solution options for user who really care about this, which you can set back to v5.12.0 behavior using `.coreGraphics`, or arbitrarily decode using `.uiKit` solution

**Comment by dreampiggy** [comment] 2022-07-16 09:07
Fired radar: FB10716439

<img width="1118" alt="截屏2022-07-16 17 06 35" src="https://user-images.githubusercontent.com/6919743/179348449-5241a740-db5f-41af-b4ce-9b9a6686af9d.png">

**Closed** 2022-07-16 11:33 UTC
Labels: apple bug, simulator

**Comment by randarnold** [comment] 2022-07-18 15:40
Looks good. Thank you.
