### ISSUE TITLE
Firebase - Crashed: com.hackemist.SDWebImageDownloader (QOS: UNSPECIFIED) - SDWebImageDownloaderOperation.m – line 193

### ISSUE THREAD

**Issue by waelsaad** [SDWebImage/SDWebImage#3124] opened 2020-11-09 01:14 UTC
### New Issue Checklist

 ✅  I have read and understood the CONTRIBUTING guide
 ✅  I have read the Documentation
 ✅  I have searched for a similar issue in the project and found none

### Issue Info

Info | Value
-- | --
Platform Name | iOS
Platform Version |  14.1.0
SDWebImage Version | 5.0.0
Integration Method | cocoapods
Xcode Version | Xcode 12
Repro rate | 96.61% Crash Free Rate - 2015 user crashes in one day, that's quite a lot.

### Issue Description and Steps

Hi, I am not sure what is hapening but we're seeing a huge load of crashes in iOS 14.x with v5.0.0. Here's the stack trace:-

```

SDWebImageDownloaderOperation.m – line 193
-[SDWebImageDownloaderOperation start]

Crashed: com.hackemist.SDWebImageDownloader (QOS: UNSPECIFIED)
0  libobjc.A.dylib                0x19abda010 objc_retain + 16
1  Foundation                     0x187dc68f0 NSKeyValueWillChange + 404
2  Foundation                     0x187dc65b8 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 432
3  Foundation                     0x187d0311c -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 72
4  Foundation                     0x187dc173c _NSSetLongLongValueAndNotify + 312
5  CFNetwork                      0x1873173b0 __CFTubeSetTubeTypeNotifier + 57112
6  SDWebImage                     0x101b71714 -[SDWebImageDownloaderOperation start] + 193 (SDWebImageDownloaderOperation.m:193)
7  Foundation                     0x187ded624 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
8  Foundation                     0x187ded0d0 __NSOQSchedule_f + 184
9  libdispatch.dylib              0x1866da834 _dispatch_block_async_invoke2 + 148
10 libdispatch.dylib              0x1866ccac8 _dispatch_client_callout + 20
11 libdispatch.dylib              0x1866cfd60 _dispatch_continuation_pop + 416
12 libdispatch.dylib              0x1866cf494 _dispatch_async_redirect_invoke + 592
13 libdispatch.dylib              0x1866dd104 _dispatch_root_queue_drain + 356
14 libdispatch.dylib              0x1866dd8e8 _dispatch_worker_thread2 + 116
15 libsystem_pthread.dylib        0x1ce9bf8cc _pthread_wqthread + 216
16 libsystem_pthread.dylib        0x1ce9c677c start_wqthread + 8
```

Any assistance would be really appreciated

Thanks,

Wael

**Comment by poiuyqwert** [comment] 2020-11-13 17:32
I am seeing the same issue using version 5.3.2, cocoapods, Xcode 12. Crashes are appearing on iOS 14+, does not appear to be happening below iOS 14.

**Comment by dreampiggy** [comment] 2020-11-16 05:00
> I am seeing the same issue using SDWebImage version 5.3.2, cocoapods, Xcode 12. Crashes are appearing on iOS 14+, does not appear to be happening below iOS 14.

Any demo can re-produce this ? This sounds like KVO's issue. But our usage for KVO seems has no issue acoorcding to Apple's documentation:

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueObserving/KeyValueObserving.html

**Comment by poiuyqwert** [comment] 2020-11-25 17:15
I think this might have been caused by this Firebase SDK issue: https://github.com/firebase/firebase-ios-sdk/issues/6734
- The SDWebImage crash started happening the same time as updating to the Firebase SDK version with the issue
- The trace was very similar to the other crashes caused by the Firebase SDK (KVO related to network requests)
- The SDWebImage crash seems to no longer happen after upgrading the Firebase SDK (only been a couple days with no crashes, but seems very promising)

**Comment by dreampiggy** [comment] 2020-11-26 03:47
Thanks for your reply. Seems this was caused by Firebase and NSURLSessioni. I'll close this and link to that Firebase issue.

**Closed by dreampiggy** 2020-11-26 03:47 UTC
