### ISSUE TITLE
iOS 17/macOS 14 PNG image render wrong by default, only works when disable force decode

### ISSUE THREAD

**Issue by DaoPinWang-git** [SDWebImage/SDWebImage#3605] opened 2023-09-20 05:01 UTC
original image
![20230821125431_8522](https://github.com/SDWebImage/SDWebImage/assets/18020236/6a0069f8-582c-4faf-81ae-49879df63af9)

display image
![image_1](https://github.com/SDWebImage/SDWebImage/assets/18020236/7222216d-d6c0-4acb-bbe6-6caf850a9a13)

**Comment by dreampiggy** [comment] 2023-09-20 07:13
At least, you need to provide a sample URL for reproducation and debug...

Also, the issue template should provide the version of SDWebImage and iOS version you used

**Comment by DaoPinWong** [comment] 2023-09-21 08:10
@dreampiggy  sorry...
```
    lazy var cImageView: UIImageView = {
        let imageView = UIImageView()
        imageView.sd_setImage(with: URL(string: "https://user-images.githubusercontent.com/18020236/269165495-6a0069f8-582c-4faf-81ae-49879df63af9.png")) { image, _, _, url in

        }
        return imageView
    }()
```
image url: https://user-images.githubusercontent.com/18020236/269165495-6a0069f8-582c-4faf-81ae-49879df63af9.png

iOS: 17.0; SDWebImage: 5.18.1

**Comment by dreampiggy** [comment] 2023-09-21 08:52
Seems not reproducible in our SDWebImage Demo. I guess it's because your own project's code, for example you use some template image or filder, which effect the rendering result.

![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/5169d532-7d8f-4748-81b9-074c7a2edcec)

**Comment by DaoPinWong** [comment] 2023-09-21 17:59
<img width="1398" alt="image" src="https://github.com/SDWebImage/SDWebImage/assets/18020236/82623436-b0a3-461c-b4f3-d8c111c58fb0">
@dreampiggy  You need to use iOS 17 debug

**Comment by dreampiggy** [comment] 2023-09-22 01:39
I mean, is this behavior different from Apple's other native App ? Like Photos or Preview, and even on macOS 16

If not, it's not SDWebImage's bug, it's Apple's bug, you'd better to fire radar to Apple

**Comment by dreampiggy** [comment] 2023-09-22 01:40
Or you can choose not to use ImageIO (Apple's Image decoder), use the open-source libpng instead.https://github.com/glennrp/libpng

**Comment by dreampiggy** [comment] 2023-09-22 01:53
![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/4f8f1ce4-9dd0-4098-8242-3a7ba539586a)

Give you the demo and run by yourself, is this behavior different from SDWebImage ? Note the background view use `.black` color and your PNG contains alpha channel

**Comment by dreampiggy** [comment] 2023-09-22 01:56
I guess this is not bug. The PNG is alpha image so it can blend with the background. I don't think these two render result is different, because `They are on different background`

You should not use that `lldb` debugger render to blame me, it has another background view which is grey, not the white one

**Comment by DaoPinWang-git** [comment] 2023-09-22 03:05
sorry my fault，i tried to download the image using the iOS API, but got a different result from SDWebImage

        imageView1.frame = CGRect(x: 10, y: 110, width: 295, height: 73)
        view.addSubview(imageView1)
        
        imageView2.frame = CGRect(x: 10, y: 200, width: 295, height: 73)
        view.addSubview(imageView2)
        
        
        imageView1.sd_setImage(with: URL(string: "https://user-images.githubusercontent.com/18020236/269165495-6a0069f8-582c-4faf-81ae-49879df63af9.png")) { image, _, _, url in
        }
        
        
        let url = URL(string: "https://user-images.githubusercontent.com/18020236/269165495-6a0069f8-582c-4faf-81ae-49879df63af9.png")!

        let session = URLSession.shared
        let task = session.dataTask(with: url) { (data, response, error) in
            if let error = error {
                print("Error: \(error)")
                return
            }
            
            guard let data = data,
                  let image = UIImage(data: data)
                  else {
                    print("Invalid image data")
                    return
            }
            
            DispatchQueue.main.async {
                self.imageView2.image = image
            }
        }

        task.resume()


in iOS 16.4 simulator
![image](https://github.com/SDWebImage/SDWebImage/assets/18020236/fc3fc19c-5ef5-4dd2-9a8d-3d9ba5b5c66f)
 
in iOS 17.0 simulator
![image](https://github.com/SDWebImage/SDWebImage/assets/18020236/eddd6b7c-800e-4b90-9fce-e550709ae01b)

**Comment by dreampiggy** [comment] 2023-09-22 04:15
Disable the force decode and try again. Use that "avoideDecodeImage"


I guess this maybe something bug of CoreAnimation

**Comment by dreampiggy** [comment] 2023-09-22 06:59
Can reproduce on iOS 17 simulator. There are render differences when enable/disable force decode (via `avoidDecodeImage` or `imageForceDecodePolicy`)

See:

## Enable Force Decode (default)

<img width="1491" alt="截屏2023-09-22 14 56 49" src="https://github.com/SDWebImage/SDWebImage/assets/6919743/12497758-0999-46dc-8753-7b95457d710d">

## Disable Force Decode 

<img width="1512" alt="截屏2023-09-22 14 57 28" src="https://github.com/SDWebImage/SDWebImage/assets/6919743/1636d246-42e2-42ed-af32-24aac6786780">

**Comment by DaoPinWang-git** [comment] 2023-09-22 07:15
thx!!!  👏👏👏 🎉🎉🎉

**Comment by dreampiggy** [comment] 2023-09-22 07:20
Open currently, seems need to fire radar to Apple or find some way for better workaround.

**Comment by dreampiggy** [comment] 2023-09-22 07:40
# FB13196663

![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/b6a160d1-b13e-4c73-81fe-642a95b12adb)

**Comment by lyandy** [comment] 2023-10-09 03:05
It seems like there are some bugs in `UIGraphicsImageRenderer `
A very simple demo is here:  [ios_17_image_test](https://github.com/lyandy/ios_17_image_test)
It's not SDWebImage's bug

**Comment by dreampiggy** [comment] 2023-10-30 07:06
Update:

It's not bug of UIKit team actually :)

It's bug of ImageIO team, the decoded CGImage contains **Wrong BitmapInfo**, which store the RGB into pre-multiplied form (which means, each *R* is actually *R * Alpha*).

It should use the `kCGImageAlphaPremultipliedFirst` or `kCGImageAlphaPremultipliedFirst` to indicate the consumer (We and UIKit team), but however, then return the `kCGImageAlphaNoneSkipLast` or `kCGImageAlphaNoneSkipFirst`

A really really stupid and shit code quality.

**Comment by dreampiggy** [comment] 2023-10-30 07:24
# Left iOS 16, Right iOS 17

![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/e1310058-bff6-4b89-8636-192ee3459275)

The first RGB pixel value is not equal, the iOS 17 one seems **Premultiplied** the alpha value, which makes each pixel RGB become *smaller* (or in visible, ligher)

**Comment by dreampiggy** [comment] 2023-10-30 07:27
Pick the first pixel for example:

The alphaInfo shows the CGImage use **RGBA8888** and non-premultiplied, let check:

# iOS 16
+ R: 154
+ G: 231
+ B: 231
+ A: 50

# iOS 17
+ R: 30
+ G: 45
+ B: 45
+ A: 50

**Comment by dreampiggy** [comment] 2023-11-01 10:12
Apple still don't reply for this issue. I re-submit with a new radar FB13322401
https://github.com/dreampiggy/iOS17IndexedPNGDecodeBug

**Comment by dreampiggy** [comment] 2023-11-15 08:11
This should be fixed (hacked) by #3634

**Closed by dreampiggy** 2023-11-15 08:11 UTC
Labels: apple bug, ios17, png

**Comment by dreampiggy** [comment] 2023-11-16 11:04
Finally released [5.18.5](https://github.com/SDWebImage/SDWebImage/releases/tag/5.18.5)

@DaoPinWang-git @lyandy  Please have a try. This workaround only make all PNG decoded from SDWebImage works, but not using the hook for system SDK, which need Apple to fix.

**Comment by dreampiggy** [comment] 2023-12-01 03:09
@jiangxiaopeng 
Or if you believe this is still something not handled by SDWebImage, provide a demo for me to invesitgate using the real device. (Also, with your iPhone model and OS version)

I guess there are something mismatch between simulator and real device

**Comment by dreampiggy** [comment] 2024-01-10 10:58
@jiangxiaopeng

You're correct. Use 5.18.9, the final old PR contains typo and only enabled in Debug configuration 😃

**Comment by jiangxiaopeng** [comment] 2024-03-13 09:14
hah, It's not SDWebImage's bug, 
![Uploading 10d9dbec-69b9-43a6-967d-fe3b2985f90f.png…]()

**Comment by MichaelSSY** [comment] 2024-04-25 02:16
> Can reproduce on iOS 17 simulator. There are render differences when enable/disable force decode (via `avoidDecodeImage` or `imageForceDecodePolicy`)
> 
> See:
> 
> ## Enable Force Decode (default)
> <img alt="截屏2023-09-22 14 56 49" width="1491" src="https://private-user-images.githubusercontent.com/6919743/269856242-12497758-0999-46dc-8753-7b95457d710d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mjk2MzgsIm5iZiI6MTcxMzkyOTMzOCwicGF0aCI6Ii82OTE5NzQzLzI2OTg1NjI0Mi0xMjQ5Nzc1OC0wOTk5LTQ2ZGMtODc1My03Yjk1NDU3ZDcxMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDMyODU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQ4Y2JhNTk4YzBiNWZiOGJlYjU3NDE3N2E4ZmQ5ZDFlNDBiNzc0ZjkwZDkyNmFkMzczMTVhZmY3NDAxODNlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KzKfz3VWpSLL5aSc1z0RHRhhkU0bdfF7ShUAGEYBRLw">
> ## Disable Force Decode
> <img alt="截屏2023-09-22 14 57 28" width="1512" src="https://private-user-images.githubusercontent.com/6919743/269856282-1636d246-42e2-42ed-af32-24aac6786780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mjk2MzgsIm5iZiI6MTcxMzkyOTMzOCwicGF0aCI6Ii82OTE5NzQzLzI2OTg1NjI4Mi0xNjM2ZDI0Ni00MmUyLTQyZWQtYWYzMi0yNGFhYzY3ODY3ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDMyODU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTRjMTliNDJkOWRjYjQ4OTg3YzQ3N2IwNTM5ZGRiNDQyNGE1ZTc4ODRlNjVhYTFiMTZkNzY4NDQyMzdkNjY4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.utsx-ZoX3wWddeEyTnv4TuwNRMhdkVNyzClp2GjfasU">
> ## Change Force Decode Solution
> ![image](https://private-user-images.githubusercontent.com/6919743/269857358-3f77299f-8533-4823-9bce-744c05701f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mjk2MzgsIm5iZiI6MTcxMzkyOTMzOCwicGF0aCI6Ii82OTE5NzQzLzI2OTg1NzM1OC0zZjc3Mjk5Zi04NTMzLTQ4MjMtOWJjZS03NDRjMDU3MDFmOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDMyODU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ5M2MxMTdlNDBkOGY2ZjhiZjU4ZmM4OWUyMGFlNDM0YTM3MGZhNTZmMjgwMDg4NTgwYWEyOWQ4MWZlYzUxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x_ZjXSCNcQk-5a9h7Z-bVPz0oq_MOvYwhxunyw8Loqk)
> 
> ```
> SDImageCoderHelper.defaultDecodeSolution = .uiKit
> ```
> 
> You can also use this to force enable the UIKit (`UIImage.prepareForDisplay`) decode solution, which also works. Only the old `CoreGraphics` based decode solution does not work.



I have found that if placeholderImage is set, there may still be issues. Could you please help me check the following settings:

let URL=URL (string:“ https://user-images.githubusercontent.com/18020236/269165495-6a0069f8-582c-4faf-81ae-49879df63af9.png )!
let image=SDImageCache. shared. imageFromCache (forKey: URL. absoluteString)
self. imageView1. sd_setImage (with: URL, placeholderImage: image, options: [. avoidDecodeImage])

**Comment by MichaelSSY** [comment] 2024-04-25 03:01
It's strange. The image cached on the disk looks normal, but once it's taken out, there will be a problem displaying it

let url = URL(string: "https://user-images.githubusercontent.com/18020236/269165495-6a0069f8-582c-4faf-81ae-49879df63af9.png")!
let image = SDImageCache.shared.imageFromCache(forKey: url.absoluteString)
self.imageView2.image = image

**Comment by soniccat** [comment] 2024-08-21 09:22
@dreampiggy  Hi, I've probably come across the same problem related to UIGraphicsImageRenderer. For the same image on iOS 15 cgImage.alphaInfo was equal to .premultipliedLast but on iOS 17 it became .premultipliedFirst. After digging a bit further I figured out that I also needed to check cgImage.bitmapInfo as on iOS 15 it was default and on iOS 17 it became kCGImageByteOrder32Little. That meant I needed to read argb bytes in reversed order to archive the same result I have on iOS 15.

**Comment by dreampiggy** [comment] 2024-08-21 09:46
@soniccat You're correct. This is Apple's ImageIO PNG decoder bug, we already workaround this. (only image generated from SDWebImage, we can not save the world and swizzle other's API)

The bug reproduce demo can be found at my repo: https://github.com/dreampiggy/iOS17IndexedPNGDecodeBug

**Comment by dreampiggy** [comment] 2025-02-17 07:39
> I figured out that I also needed to check cgImage.bitmapInfo as on iOS 15 it was default and on iOS 17 it became kCGImageByteOrder32Little (32-bit, little endian format.)

We already consider byte order in our parsing tool and image decoder. But it's still wrong, and indeed Apple's Bug
