### ISSUE TITLE
Animated image is not working in a Text (using text attachment)

### ISSUE THREAD

**Issue by yamanetaisei** [SDWebImage/SDWebImage#3737] opened 2024-08-08 01:16 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        |  17.0 ~ (my env is 17.2)
 SDWebImage Version      |  5.19.1 (installed SDWebImageSwiftUI ver 3.0.2)
 Integration Method      | SPM
 Xcode Version           | 15.2
 Repro rate              |  100%
 Repro with our demo prj | no
 Demo project link       |  https://gist.github.com/yamanetaisei/fb2ac36511c0d172e6fc2dc9aa449122

### Issue Description and Steps

I use this library as a TextAttachment.

UITextVeiw is placed in the List of SwiftUI. And it is used in `NSMutableAttributedString(attachment: )`.
At first the animation plays correctly. However, when scrolling down and back up, all animation stops.
I would like the animation to always play when it is on the screen, but I don't know how to do that.

Also, [SubviewAttachingTextView](https://github.com/vlas-voloshin/SubviewAttachingTextView) is used to make `imageView.sd_setImage()` a TextAttachment

Please see this for implementation details. I made sample code
https://gist.github.com/yamanetaisei/fb2ac36511c0d172e6fc2dc9aa449122

https://github.com/user-attachments/assets/6c91811d-9f5c-426e-b387-82f68c6d9729

**Comment by dreampiggy** [comment] 2024-08-08 06:29
By design. Ask Apple to support this case ([NSTextAttachment](https://developer.apple.com/documentation/uikit/nstextattachment))

**Comment by dreampiggy** [comment] 2024-08-08 06:30
Even you use `UIImage animatedImageWithImages`, the behavior is the same.

This is Apple's Platform API limit. And we can not do customization unlike `SDAnimatedImageView`

**Comment by dreampiggy** [comment] 2024-08-08 07:00
Actually, you don't need a `UIImageView` or something and call `sd_setImage`

You can just use URLSession or our `SDWebImageLoader` to load an `UIImage` of GIF, which is actually a `_UIAnimatedImage`

From your code line: https://gist.github.com/yamanetaisei/fb2ac36511c0d172e6fc2dc9aa449122#file-sdwebimageasatextattachment-swift-L137

**Comment by yamanetaisei** [comment] 2024-08-08 08:10
@dreampiggy 
Thanks for your kind response.

Your [advice](https://github.com/SDWebImage/SDWebImage/issues/3737#issuecomment-2275091941) on implementation was very helpful.

This is off topic, if I use `ScrollView + LazyVStack` instead of List like this, I don't have this problem 😕 
I'm writing to share knowledges.

``` swift
struct ContentView: View {
    var body: some View {
        ScrollView {
            LazyVStack {
                ForEach(0..<100) { _ in
                    Row()
                }
            }
        }
        .listStyle(.plain)
    }
}
```

**Comment by dreampiggy** [comment] 2024-08-09 02:12
> This is off topic, if I use ScrollView + LazyVStack instead of List like this, I don't have this problem

What does this mean ?

NSTextAttachment does not support animated image at all. What ever it's a `_UIAnimatedImage` or `SDAnimatedImage`

Can you show your debugger output ?

**Comment by dreampiggy** [comment] 2024-08-09 02:22
Maybe I can spend some time to debug in myself...

**Comment by dreampiggy** [comment] 2024-08-09 02:36
If you want to talk about the details of how `UIImageView` render the animation, and how `_UIAnimatedImage` works, search the issue and there're something I talked years ago.

It impl use the CoreAnimation (`CAAnimation`), added the animation onto the native UIView's layer.
When the view appears (on `UIImageView`'s `didMoveToWindow` callback), it trigger the animation refresh (like, restart from the first frame animation)

However, I don't know whether SwiftUI's optimization break this. Or how the `UITextView` do this. We need to disassemble UIKit's code

**Comment by dreampiggy** [comment] 2024-08-09 07:57
@yamanetaisei 

Seems I misunderstand your use case. Because you use `NSTextAttachment` which confused me.

Your code use another third-party lib `SubviewAttachingTextView`

This lib contains a API `instantiateView(for attachment: SubviewTextAttachment, in behavior: SubviewAttachingTextViewBehavior) -> UIView`

**It does not use NSTextAttachment.image at all!**

It use added it into the subview tree and render.

Your problem is, you misuse the UIImageView to make it `startAnimating when disappear`

**Comment by dreampiggy** [comment] 2024-08-09 08:20
Fixed for you. Read all the comments I marked as `[DreamPiggy]` to understand the reason:

```swift
import SwiftUI
import UIKit
import SDWebImageSwiftUI
import SubviewAttachingTextView


let url: URL = URL(string: "https://www.easygifanimator.net/images/samples/texteffects.gif")!


struct ContentView: View {
    var body: some View {
        List {
            ForEach(0..<100) { _ in
                Row()
            }
        }
        .listStyle(.plain)
    }
}

struct Row: View {

    @State var height: CGFloat = .zero
    var arrtText: NSMutableAttributedString = .init()
    let textView = SubviewAttachingTextView()

    init() {
        self.arrtText = makeAttrText()
    }

    var body: some View {
        WrappedTextView(
            attributedText: arrtText,
            calculatedHeight: $height,
            textView: textView
        )
        .frame(minHeight: height)
    }

    // attach gif
    func makeAttrText() -> NSMutableAttributedString {
        let result = NSMutableAttributedString()
        result.append(.init(string: "Hello SDWebImage in Text "))

        let attchedString = NSMutableAttributedString(
            attachment:  RemoteImageAttachment(
                url: url,
                size: .init(width: 18, height: 18)
            ) {
                didLoadImage()
            }
        )
        result.append(attchedString)
        return result
    }

    // reload textView layout
    func didLoadImage() {
        textView
            .layoutManager
            .invalidateLayout(
                forCharacterRange: NSRange(location: 0, length: textView.textStorage.length),
                actualCharacterRange: nil
            )
    }
}

// for use UITextView
struct WrappedTextView: UIViewRepresentable {
    var attributedText: NSMutableAttributedString
    @Binding var calculatedHeight: CGFloat

    typealias UIViewType = SubviewAttachingTextView
    let textView: SubviewAttachingTextView

    func makeUIView(context: Context) -> UIViewType {
        textView.backgroundColor = .clear
        textView.allowsEditingTextAttributes = true
        textView.isEditable = false
        textView.isScrollEnabled = false
        textView.showsVerticalScrollIndicator = false
        textView.showsHorizontalScrollIndicator = false
        textView.textContainer.lineBreakMode = .byCharWrapping
        textView.textContainerInset = .init(top: 5, left: .zero, bottom: .zero, right: .zero)
        textView.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
        return textView
    }

    func updateUIView(_ uiView: UIViewType, context: Context) {
        uiView.attributedText = attributedText
        DispatchQueue.main.async {
            calculatedHeight = uiView.sizeThatFits(CGSize(width: uiView.bounds.width, height: CGFloat.greatestFiniteMagnitude)).height
        }
    }
}

class RemoteImageAttachment: SubviewTextAttachment {
    let provider: TextAttachedViewProvider
    init(url: URL, size: CGSize, didLoadImage: @escaping () -> Void) {
        provider = RemoteImageAttachmentProvider(url: url, size: size) { didLoadImage() }
        super.init(viewProvider: provider)
    }

    @available(*, unavailable)
    required init?(coder _: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

// You can use SDAnimatedImageView for better performance (on RAM)
// Or you will occur OOM because UIImageView's animation **keep all frames into RAM**
// But SDAnimatedImage will use a buffer (slide window) to decode Just-In-Time
@objcMembers
public class TextKitCompatibleUIImageView : UIImageView {
    private func checkPlay() {
        let isVisible = self.window != nil
        && self.superview != nil
        && !self.isHidden
        && self.alpha > 0.0
        if isVisible {
            // [DreamPiggy] UIImageView's buggy compatible with TextKit 1
            // [DreamPiggy] Seems TextKit has its own cache of layer, UIImageView's startAnimating added CAAnimation does not get refreshed.
            // [DreamPiggy] Do a stupid force reset image to workaround
            let image = self.image
            self.image = nil
            self.image = image
            self.startAnimating()
        } else {
            self.stopAnimating()
        }
    }
    public override func didMoveToSuperview() {
        super.didMoveToSuperview()
        checkPlay()
    }
    public override func didMoveToWindow() {
        super.didMoveToWindow()
        checkPlay()
    }
    
    public override var alpha: CGFloat {
        set {
            super.alpha = newValue
            checkPlay()
        }
        get {
            return super.alpha
        }
        
    }
    public override var isHidden: Bool {
        set {
            super.isHidden = newValue
            checkPlay()
        }
        get {
            return super.isHidden
        }
    }
}

private class RemoteImageAttachmentProvider: TextAttachedViewProvider {
    let url: URL
    let size: CGSize

    let imageHeight = 24.0
    var aspectRatio: CGFloat?

    let placeholder = UIImage(systemName: "rectangle")
    let didLoadImage: () -> Void

    init(url: URL, size: CGSize, didLoadImage: @escaping () -> Void) {
        self.url = url
        self.size = size
        self.didLoadImage = didLoadImage
    }

    @available(*, unavailable)
    required init?(coder _: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func instantiateView(for _: SubviewTextAttachment, in _: SubviewAttachingTextViewBehavior) -> UIView {
        // [DreamPiggy] This `SubviewAttachingTextView` API is garbage, it does not considerate the dynamic view which need refresh (like `cellForRowAtIndexPath:` on UITableView)
        // [DreamPiggy] You can use subview or KVO of UIView's visibility status to force start animating/stop animating
        let view = TextKitCompatibleUIImageView() // or SDAnimatedImageView
        view.contentMode = .scaleAspectFit
        view.layer.minificationFilter = .trilinear

        // set image url
        view.sd_setImage(with: url, placeholderImage: placeholder, options: []) { [weak self] image, _, _, _ in
            guard let self else { return }
            guard let image else { return }
            self.aspectRatio = image.size.width / image.size.height
            let imageWidth: CGFloat = if let aspectRatio {
                (imageHeight * aspectRatio)
            } else {
                self.imageHeight
            }
            // change size to display in text
            // [DreamPiggy] Wrong, SDWebImage's callback is guranteed on main queue
            // [DreamPiggy] unless you pass context .callbackQueue
//            DispatchQueue.main.async { [weak self] in
//                guard let self else { return }
                view.frame.size = CGSize(width: imageWidth, height: self.imageHeight)
                didLoadImage()
//            }
        }
        view.clipsToBounds = true
        return view
    }

    func bounds(for _: SubviewTextAttachment, textContainer _: NSTextContainer?, proposedLineFragment _: CGRect, glyphPosition _: CGPoint) -> CGRect {
        let imageWidth: CGFloat = if let aspectRatio {
            (imageHeight * aspectRatio)
        } else {
            imageHeight
        }
        return .init(x: 0, y: -5, width: imageWidth, height: imageHeight)
    }
}

```

**Comment by dreampiggy** [comment] 2024-08-09 08:55
RAM compare between SDAnimatedImageView vs UIImageView, you can try super large GIF like this one: https://raw.githubusercontent.com/liyong03/YLGIFImage/master/YLGIFImageDemo/YLGIFImageDemo/joy.gif

### SDAnimatedImageView
![image](https://github.com/user-attachments/assets/9a782e24-4a95-4d5c-91e2-11ed46f203ba)



### TextKitCompatibleUIImageView (UIImageView)
![image](https://github.com/user-attachments/assets/d6931aae-f367-42e4-81e0-646dc29c3e31)

**Comment by yamanetaisei** [comment] 2024-08-10 15:01
@dreampiggy 

I read the thread.
Thank you so much for solving my problem. 😄 

I am sorry for the confusion I have caused by my bad way of communicating.
I did not understand SubviewAttachingTextView in detail either.

This discussion has been a good learning and would make a great sample for implementing Animated Emoji 👍

**Closed** 2024-08-12 03:45 UTC
Labels: usage, animated image, By Design
