### ISSUE TITLE
JPG image data is not visible with `SDAnimatedImage(data:)`/`AnimatedImage(data:)`(SwiftUI) while png data works fine

### ISSUE THREAD

**Issue by hstdt** [SDWebImage/SDWebImage#3625] opened 2023-10-20 09:33 UTC
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name        |  iOS
 Platform Version     |  15.0, 17.0
 SDWebImage Version    | 5.18.3
 Integration Method  |   SPM
 Xcode Version        |   Xcode 15.0 / Xcode 15.1 Beta
 Repro rate         |     all the time (100%)
 Repro with our demo prj | not sure
 Demo project link       |   [SDDisplayDemo.zip](https://github.com/SDWebImage/SDWebImage/files/13052687/SDDisplayDemo.zip)

### Issue Description and Steps

Running demo project.  JPG image data is not visible with `SDAnimatedImage(data:)`/`AnimatedImage(data:)`(SwiftUI) while png data works fine
PS: I'm finding a common way to display image by data without local/remote url.

![CleanShot 2023-10-20 at 17 29 47](https://github.com/SDWebImage/SDWebImage/assets/10215098/b5755aa4-a80c-4e9b-b25e-132a4da7e30a)

**Comment by dreampiggy** [comment] 2023-10-21 07:55
> JPG image data is not visible with

Seems by design ? The `SDAnimatedImage` init the `JPEG` data may return nil....I guess.

Because that `animatedImageFrameCount` is 1

**Comment by dreampiggy** [comment] 2023-10-21 07:59
If you'd like `A drop-in` replacement which can display either animated or non-animated, maybe we need to change this behavior by modify the `SDAnimatedImage` source code here.

**Comment by dreampiggy** [comment] 2023-10-21 08:03
I test again and it can render the JPEG image, what's the version of SwiftUI repo did you use ?
![image](https://github.com/SDWebImage/SDWebImage/assets/6919743/f81860b4-18f0-4595-aba7-5f780afa26a9)

> https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_1.jpg

**Comment by dreampiggy** [comment] 2023-10-21 08:04
Or you means, JPEG via `AnimatedImage(data:)`, not JPEG via `AnimatedImage(url:)` ?

**Comment by dreampiggy** [comment] 2023-10-21 08:11
A quick fix is in the SwiftUI repo, when the `SDAnimatedImage` init returns nil, use `UIImage` instead.

**Comment by hstdt** [comment] 2023-10-21 08:28
@dreampiggy In the demo project, `SDAnimatedImageView` is wrapped by UIViewRepresentable, so it is only a swiftui problem but also maybe a UIKit problem. `imageView.backgroundColor` works, but `imageView.image` seems not working.

![CleanShot 2023-10-21 at 16 23 35](https://github.com/SDWebImage/SDWebImage/assets/10215098/934ad80b-b5e6-4428-82ef-2f63d9151f71)

![CleanShot 2023-10-21 at 16 18 09](https://github.com/SDWebImage/SDWebImage/assets/10215098/4113bdb6-be19-48c3-9b6b-0958ab4c4396)

=== updated demo project

[SDDisplayDemo-1.zip](https://github.com/SDWebImage/SDWebImage/files/13060275/SDDisplayDemo-1.zip)

**Comment by dreampiggy** [comment] 2023-10-21 08:35
@hstdt Try that PR's branch, or copy the code for `AnimatedImage.swift` and re-test again. I think it solve the issues.

**Comment by dreampiggy** [comment] 2023-10-21 08:36
The behavior will not changes (at least in SDWebImage 5.x). If you init `SDAnimatedImage` failed, you MUST init `UIImage` and re-try again.

Even for UIKit code, you must do like this:

```
            var image: PlatformImage? = SDAnimatedImage(data: data, scale: imageModel.scale)
            if image == nil {
                // For static image, use UIImage as defaults
                image = PlatformImage(data: data)
            }
sdaniamtedImageView.image = image
```

**Comment by dreampiggy** [comment] 2023-10-21 08:43
If you have question about the design, check the original post: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50

`SDAnimatedImage` is designed to be used with `AnimatedImage` (from its naming). For JPEG it's not animated, so return nil for `init(data:)`

SDWebImage itself has a util entry called `SDImageLoaderDecodeImageData` for developer who want to load itself (or `SDImageCacheDecodeImageData` for cache), those handled the case like this using `UIImage` as defaults condition

**Comment by dreampiggy** [comment] 2023-10-21 08:49
> The behavior will not changes (at least in SDWebImage 5.x). If you init `SDAnimatedImage` failed, you MUST init `UIImage` and re-try again. This is why we `Subclass UIImage`
> 
> Even for UIKit code, you must do like this:
> 
> ```swift
> var image: UIImage? = SDAnimatedImage(data: data, scale: imageModel.scale)
> if image == nil {
>     // For static image, use UIImage as defaults
>     image = UIImage(data: data)
> }
> sdaniamtedImageView.image = image
> ```

Oh...Seems this is not correct, compared to SDWebImage Core logic.

Should use this API instead:

```
var image: UIImage? = SDAnimatedImage(data: data, scale: imageModel.scale)
if image == nil {
    // For static image, use UIImage as defaults
    image = UIImage.sd_image(with: data) // This API is from us and supports WebP/AVIF/PDF or other format Apple don't support
}
sdaniamtedImageView.image = image
```

**Comment by dreampiggy** [comment] 2023-10-21 08:58
Are you really want a `YYImage` like (which means, even for JPEG image, it returns non-nil), and the `animatedImageFrameCount == 1` or `animatedImageAtIndex:0` will return `self` ?

If so, we can change this behavior to like that in the SDWebImage v6.0, I guess it's more suitable.

5.x still keeps the behavior `if image is not animated, return nil instead`

**Comment by hstdt** [comment] 2023-10-21 09:06
@dreampiggy PR fixed it, thank you!

![CleanShot 2023-10-21 at 16 59 48](https://github.com/SDWebImage/SDWebImage/assets/10215098/575de9e0-19dc-4161-87e2-5ca67f14aa6d)

> Are you really want a YYImage like (which means, even for JPEG image, it returns non-nil), and the animatedImageFrameCount == 1 or animatedImageAtIndex:0 will return self ?

In my opinion, return self should be a better behavior, because when png works, developers may missing testing other image such as jpeg, heic or unkown picture format in the future.

Final codes:
[SDDisplayDemo-Final.zip](https://github.com/SDWebImage/SDWebImage/files/13060327/SDDisplayDemo-Final.zip)

**Comment by hstdt** [comment] 2023-10-21 09:13
> In my opinion, return self should be a better behavior, because when png works, developers may missing testing other image such as jpeg, heic or unkown picture format in the future.

or SDAnimatedImageView can init with data as swiftui did.

**Comment by dreampiggy** [comment] 2023-10-21 09:33
If we changes the behavior like this:

```objc
    // [SDAnimatedImage initWithData:]
    if (animatedCoder) {
        // Animated Image
        return [self initWithAnimatedCoder:animatedCoder scale:scale];
    } else {
        // Static Image (From 5.19's behavior, does not return nil)
        UIImage *image = [UIImage sd_imageWithData:data scale:scale];
        if (!image) {
            return nil;
        }
#if SD_MAC
        self = [super initWithCGImage:image.CGImage scale:MAX(scale, 1) orientation:kCGImagePropertyOrientationUp];
#else
        self = [super initWithCGImage:image.CGImage scale:MAX(scale, 1) orientation:image.imageOrientation];
#endif
    }
```


+ For static image coder, it's easy and OK to support

Because the `[UIImage sd_imageWithData:data scale:scale];` will never return a `_UIAnimatedImage` or other internal subclass (not only we subclass UIImage, Apple subclass UIImage as well :))

+ For animated image, who does not conforms `SDAnimatedImageCoder`

This may cause a suck question. If I write a bad animated coder like the old https://github.com/SDWebImage/SDWebImageBPGCoder

Because it does not conforms to `SDAnimatedImageCoder`, then it will return nil. But when use `[UIImage sd_imageWithData:data scale:scale];` it will return a `_UIAnimatedImage`

However, since both we (SDAnimatedImage) and Apple (_UIAnimatedImage) subclass UIImage, how do we return ? 

This line of code cause issues...

```
self = [super initWithCGImage:image.CGImage scale:MAX(scale, 1) orientation:image.imageOrientation];
```

**Comment by dreampiggy** [comment] 2023-10-21 09:38
The suck thing because of subclassing is that, `SDAnimatedImage(data:)`, is not a class-cluster. So I suggest you (as caller) to choose different subclass you want.

SDAnimatedImage initializer can not return a `_UIAnimatedImage` instance, but if you really need the `_UIAnimatedImage` this will cause different behavior between this two code pieces.

### This one
```
var image: UIImage? = SDAnimatedImage(data: data)
if image == nil {
    // For static image, use UIImage as defaults
    image = UIImage.sd_image(with: data) // <-------------!!! This can be a `_UIAnimatedImage` as well
}
```

### Another one
```
var image: UIImage? = SDAnimatedImage(data: data) // with the new changes, this will always return either `UIImage` or `SDAnimatedImage`
// <---------!!! This never be a `_UIAnimatedImage` instance
```

**Closed** 2023-10-21 09:52 UTC
Labels: swiftui

**Comment by hstdt** [comment] 2023-10-21 10:12
@dreampiggy  If code changed to url, everything is ok. And I believe `_UIAnimatedImage` related questions should not affect the API design. `URL` or `Data` logic may be better in cross platform situation today, better than add some if/else to `uiimage/nsimage`.

![CleanShot 2023-10-21 at 18 03 55](https://github.com/SDWebImage/SDWebImage/assets/10215098/b35fb910-5700-4dd7-bebc-aecb1d65dafa)

**Comment by dreampiggy** [comment] 2023-10-21 10:15
@hstdt See https://github.com/SDWebImage/SDWebImage/pull/3626

Read the code (Objective-C) is that match what you want ?

**Comment by dreampiggy** [comment] 2023-10-21 10:17
> URL or Data logic may be better in cross platform situation today, better than add some if/else to uiimage/nsimage.

Actually, SDAnimatedImage does not supports `URL` initializer, right ?

The `AnimatedImage` in SwiftUI is just a `SDAnimatedImageView+SDAnimatedImage+Logic` combination, not a simple class.

**Comment by dreampiggy** [comment] 2023-10-21 10:21
OK...I get what you means.

You means the `fileURL` and the `Data(contentsOf: fileURL)` should share the same logic ?

## Just NO. It's not guaranteed.

For a simple question, does that `Data` initializer supports caching ? :)

**Comment by hstdt** [comment] 2023-10-21 10:30
> OK...I get what you means.
> 
> You means the `fileURL` and the `Data(contentsOf: fileURL)` should share the same logic ?
> 
> ## NO. It's not guaranteed.
> For a simple question, does that `Data` initializer supports caching ? :) And for fileURL, it actually load in **Async** For data, it actually load in **Sync** and blocking the caller thread.

Not same logic between url and data. I mean same image should be displayed same whatevar is is data or url.

**Comment by hstdt** [comment] 2023-10-21 10:44
> @hstdt See #3626
> 
> Read the code (Objective-C) is that match what you want ?

Yes, now `UIImage.sd_image(with: data)` is unnecessary. ❤️❤️

![CleanShot 2023-10-21 at 18 42 49](https://github.com/SDWebImage/SDWebImage/assets/10215098/28fa20a9-1507-4b4e-b045-e3a3f5004580)

**Comment by dreampiggy** [comment] 2023-10-21 10:54
> > @hstdt See #3626
> > Read the code (Objective-C) is that match what you want ?
> 
> Yes, now `UIImage.sd_image(with: data)` is unnecessary. ❤️❤️
> 
> ![CleanShot 2023-10-21 at 18 42 49](https://user-images.githubusercontent.com/10215098/277103249-28fa20a9-1507-4b4e-b045-e3a3f5004580.png)

Are you in hurry about this PR ? I have another feature to implements and want to release in 5.19.0 of SDWebImage as well.

If you can wait, I'll release 5.19.0 in the next weak (for old version you still need that conditional check for nil SDAnimatedImage) 

For that SwiftUI `AnimatedImage`, it's already been fixed and released, if you can always use SwiftUI, prefer that `SwiftUI.AnimatedImage` instead.

**Comment by hstdt** [comment] 2023-10-21 11:03
> Are you in hurry about this PR ? I have another feature to implements and want to release in 5.19.0 of SDWebImage as well.

Sure, merge  to 5.19.0 is a good idea,  and my project is using swiftui version.

**Comment by dreampiggy** [comment] 2023-10-21 11:08
I means, the release date of SDWebImage 5.19.0 may be delayed into next weak (2023-19-28)

Because there are some other changes (not related to this PR, but which deprecate some APIs so it need to bump minor versions....😂). I don't want to release 5.19.0 today and another 5.20.0 next weak.

If you can't wait to use this #3626, you can currently use the commit dependency (as you shown in screenshot) to test your project.

**Comment by dreampiggy** [comment] 2023-10-27 08:20
Decide to release 5.18.4 for now. That 5.19.0 is still delayed for some un-resolved issues.

You can have a try with the release version instead of commit hash dependency @hstdt
